name: genaihub-devops-project

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: genaihub-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/blackbox.yml:/etc/prometheus/blackbox.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - genaihub-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: genaihub-grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    networks:
      - genaihub-network
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: genaihub-node-exporter
    ports:
      - "9100:9100"
    networks:
      - genaihub-network
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: genaihub-cadvisor
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - genaihub-network
    restart: unless-stopped

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: genaihub-blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./monitoring/prometheus/blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    networks:
      - genaihub-network
    restart: unless-stopped
