apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: genaihub-frontend
spec:
  type: LoadBalancer
  selector:
    app: genaihub-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
